
title: My Portfolio
email: menendevs@gamil.com
domain: menendevs.com
url: "https://menendevs.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# plugins:
  # - jekyll-seo-tag
